/*
DML COMMANDS                   DDL COMMANDS
1.SELECT                        1.CREATE
2.INSERT                        2.ALTER
3.DELETE                        3.DROP
4.UPDATE                        4.TRUNCATE

DML -- Data Manipulation Language
DDL -- Data Defination Language
*/

CREATE DATABASE CODEBIN;  # CODEBIN - DATABASE NAME
USE CODEBIN;

CREATE TABLE STUDENT(
	NAME VARCHAR(100),
    CITY VARCHAR(30),
    AGE INT
);

SELECT * FROM STUDENT;

INSERT INTO STUDENT VALUES("RAM","CHENNAI",24);
INSERT INTO STUDENT VALUES("JANU","TRICHY",19);

INSERT INTO STUDENT(NAME,CITY) VALUES("VISHAL","CHENNAI");


-- VIEW TABLE
SELECT * FROM STUDENT;
SELECT NAME FROM STUDENT;
SELECT CITY FROM STUDENT;
SELECT AGE FROM STUDENT;
SELECT NAME,CITY FROM STUDENT;

# ADD MORE RECORDS
 INSERT INTO STUDENT VALUES("JANVY","SALEM",19),("KUMARI","VIZAG",22),
 ("RADHA","SALEM",22),("LOKESK","MADURAI",30),("KANAGRAJ","CHENNAI",28);
 
 -- FILTER 
 
SELECT * FROM STUDENT
WHERE CITY = "CHENNAI";

SELECT * FROM STUDENT
WHERE CITY = "CHENNAI" AND AGE>24;

-- DELETE COMMAND
DELETE FROM STUDENT
WHERE NAME = "VISHAL";

-- UPDATE COMMAND
UPDATE STUDENT SET AGE = 26
WHERE NAME = "KUMARI";

-- ALTER TABLE
ALTER TABLE STUDENT ADD ROLLNO INT;

UPDATE STUDENT SET ROLLNO = 24;

