CREATE TABLE STUDENT(
    ID INT PRIMARY key,
    NAME VARCHAR(30),
    GPA DECIMAL(3,2)
);

DESCRIBE STUDENT; 

DROP TABLE STUDENT; 
ALTER TABLE STUDENT ADD DEPARTMENT VARCHAR(10);
ALTER TABLE STUDENT DROP DEPARTMENT;

INSERT INTO STUDENT VALUES (1,"HARI",7.1);
INSERT INTO STUDENT VALUES (2,"KRISHNAN",8);
INSERT INTO STUDENT VALUES (3,"PRADEEP",6);
INSERT INTO STUDENT VALUES (4,"KUMAR",7);
INSERT INTO STUDENT VALUES (5,"GOPAL",2.4),
(6,"KRISHNAN",7.2),
(7,"SELVI",5.6);

INSERT INTO STUDENT(ID,NAME) VALUES(8,"ROSHAN");

SELECT * FROM STUDENT;


SELECT * FROM STUDENT;

SELECT NAME FROM STUDENT;
SELECT ID FROM STUDENT;
SELECT GPA FROM STUDENT;
SELECT NAME,GPA FROM STUDENT;